# Generated by Django 2.2.1 on 2019-05-16 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40, verbose_name='activation key')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('activated', models.BooleanField(default=False, verbose_name='activated')),
                ('moderated', models.BooleanField(default=False, verbose_name='moderated')),
                ('moderation_time', models.DateTimeField(null=True, verbose_name='moderation_time')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_profiles', to=settings.AUTH_USER_MODEL, verbose_name='moderator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'registration profile',
                'verbose_name_plural': 'registration profiles',
            },
        ),
    ]
